using Content.Client.Stylesheets;
using Content.Shared._MalinovStation.Lobby;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;

namespace Content.Client._MalinovStation.Lobby;

/// <summary>
/// One lobby tile: a framed panel with a title and a slot for its content.
/// </summary>
/// <remarks>
/// Content can be adopted from elsewhere in the UI tree; <see cref="Release"/> puts it back
/// where it came from, so the lobby screen can be rebuilt without losing controls.
/// While the player edits the layout, the header is a drag handle and offers to hide the tile, and a resizable tile
/// can be taken by its edges and corners, which light up under the pointer; the owner of the tile acts on
/// <see cref="DragPressed"/>, <see cref="DragReleased"/>, <see cref="ResizePressed"/>, <see cref="ResizeReleased"/>
/// and <see cref="HidePressed"/>.
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class MalinovLobbyTileControl : PanelContainer
{
    [Dependency] private ILocalizationManager _loc = default!;

    public const string StyleClassHeader = "MalinovLobbyTileHeader";
    public const string StyleClassHeaderAccent = "MalinovLobbyTileHeaderAccent";
    public const string StyleClassResizeHandle = "MalinovLobbyTileResizeHandle";
    public const string StyleClassResizeHandleHovered = "MalinovLobbyTileResizeHandleHovered";
    public const string FadeInKey = "malinov-lobby-tile-fade-in";
    public const float FadeInSeconds = 0.25f;

    // How opaque a hidden tile's content and a dragged tile are while editing.
    private const float FadedAlpha = 0.4f;

    // Thickness of the edge handles and size of the corner ones; the corners lie over the ends of the edges.
    private const float EdgeHandleThickness = 6f;
    private const float CornerHandleSize = 14f;

    private readonly Dictionary<MalinovLobbyTileEdges, Control> _resizeHandles = new();

    private Control? _origin;
    private Vector2i _tilePosition;
    private Vector2i _tileSize = Vector2i.One;
    private Vector2i _minTileSize = Vector2i.One;
    private Vector2i _maxTileSize = Vector2i.One;
    private bool _hasTitle;
    private bool _accented;
    private bool _editing;
    private bool _hideable = true;
    private bool _userHidden;
    private bool _dragged;
    private bool _dropTarget;

    /// <summary>
    /// The header was pressed while editing: the owner may start dragging the tile.
    /// </summary>
    public event Action<MalinovLobbyTileControl>? DragPressed;

    /// <summary>
    /// The press on the header ended while editing.
    /// </summary>
    public event Action<MalinovLobbyTileControl>? DragReleased;

    /// <summary>
    /// An edge or corner was pressed while editing: the owner may start resizing the tile by the edges it moves.
    /// </summary>
    public event Action<MalinovLobbyTileControl, MalinovLobbyTileEdges>? ResizePressed;

    /// <summary>
    /// The press on an edge or corner ended while editing.
    /// </summary>
    public event Action<MalinovLobbyTileControl>? ResizeReleased;

    /// <summary>
    /// The player asked to hide or show the tile.
    /// </summary>
    public event Action<MalinovLobbyTileControl>? HidePressed;

    /// <summary>
    /// Prototype this tile was built from, if any.
    /// </summary>
    public ProtoId<MalinovLobbyTilePrototype>? TileId { get; set; }

    /// <summary>
    /// Top left cell of the tile on the board: column, row.
    /// </summary>
    public Vector2i TilePosition
    {
        get => _tilePosition;
        set
        {
            if (_tilePosition == value)
                return;

            _tilePosition = value;
            // The board lays its tiles out by their cells.
            Parent?.InvalidateMeasure();
        }
    }

    /// <summary>
    /// Size of the tile in board cells: columns, rows.
    /// </summary>
    public Vector2i TileSize
    {
        get => _tileSize;
        set
        {
            if (_tileSize == value)
                return;

            _tileSize = value;
            Parent?.InvalidateMeasure();
        }
    }

    /// <summary>
    /// Smallest size the player may give the tile.
    /// </summary>
    public Vector2i MinTileSize
    {
        get => _minTileSize;
        set
        {
            _minTileSize = value;
            UpdateEditing();
        }
    }

    /// <summary>
    /// Largest size the player may give the tile.
    /// </summary>
    public Vector2i MaxTileSize
    {
        get => _maxTileSize;
        set
        {
            _maxTileSize = value;
            UpdateEditing();
        }
    }

    /// <summary>
    /// Whether the player may change the size of the tile.
    /// </summary>
    public bool Resizable => _minTileSize != _maxTileSize;

    /// <summary>
    /// Handles the tile is resized by, by the edges each one moves: four sides and four corners.
    /// </summary>
    public IReadOnlyDictionary<MalinovLobbyTileEdges, Control> ResizeHandles => _resizeHandles;

    /// <summary>
    /// Control currently shown in the tile.
    /// </summary>
    public Control? Content { get; private set; }

    /// <summary>
    /// Whether the tile stands out: its header switches to the accent style.
    /// </summary>
    public bool Accented
    {
        get => _accented;
        set
        {
            if (_accented == value)
                return;

            _accented = value;
            if (value)
                Header.AddStyleClass(StyleClassHeaderAccent);
            else
                Header.RemoveStyleClass(StyleClassHeaderAccent);

            // The title is styled by the header's class, but the engine restyles only the control
            // whose class changed; a stale title would keep the accent color on the plain header.
            Header.ForceRunStyleUpdate();
        }
    }

    /// <summary>
    /// Whether the player edits the lobby layout: the header becomes a drag handle, shown even without a title.
    /// </summary>
    public bool Editing
    {
        get => _editing;
        set
        {
            if (_editing == value)
                return;

            _editing = value;
            UpdateEditing();
        }
    }

    /// <summary>
    /// Whether the player may hide the tile.
    /// </summary>
    public bool Hideable
    {
        get => _hideable;
        set
        {
            if (_hideable == value)
                return;

            _hideable = value;
            UpdateEditing();
        }
    }

    /// <summary>
    /// Whether the player hid the tile. Its owner keeps it out of sight; while editing it shows faded.
    /// </summary>
    public bool UserHidden
    {
        get => _userHidden;
        set
        {
            if (_userHidden == value)
                return;

            _userHidden = value;
            UpdateEditing();
        }
    }

    /// <summary>
    /// Whether the tile is being dragged; it fades while it is.
    /// </summary>
    public bool Dragged
    {
        get => _dragged;
        set
        {
            if (_dragged == value)
                return;

            _dragged = value;
            // A fade still running would make the dragged tile opaque again.
            StopAnimation(FadeInKey);
            Modulate = value ? Color.White.WithAlpha(FadedAlpha) : Color.White;
        }
    }

    /// <summary>
    /// Whether this tile would make room for the dragged or resized tile if the player let go now.
    /// </summary>
    public bool DropTarget
    {
        get => _dropTarget;
        set
        {
            if (_dropTarget == value)
                return;

            _dropTarget = value;
            if (value)
                AddStyleClass(StyleClass.PanelDropTarget);
            else
                RemoveStyleClass(StyleClass.PanelDropTarget);
        }
    }

    public MalinovLobbyTileControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AddStyleClass(StyleClass.BackgroundPanel);
        Header.AddStyleClass(StyleClassHeader);
        TitleLabel.AddStyleClass(StyleClass.LabelHeading);

        Header.OnKeyBindDown += OnHeaderKeyBindDown;
        Header.OnKeyBindUp += OnHeaderKeyBindUp;
        HideButton.OnPressed += OnHidePressed;

        // Sides first, so the corners lie over their ends.
        AddResizeHandle(MalinovLobbyTileEdges.Left, HAlignment.Left, VAlignment.Stretch, CursorShape.HResize);
        AddResizeHandle(MalinovLobbyTileEdges.Right, HAlignment.Right, VAlignment.Stretch, CursorShape.HResize);
        AddResizeHandle(MalinovLobbyTileEdges.Top, HAlignment.Stretch, VAlignment.Top, CursorShape.VResize);
        AddResizeHandle(MalinovLobbyTileEdges.Bottom, HAlignment.Stretch, VAlignment.Bottom, CursorShape.VResize);
        AddResizeHandle(MalinovLobbyTileEdges.TopLeft, HAlignment.Left, VAlignment.Top, CursorShape.NWSEResize);
        AddResizeHandle(MalinovLobbyTileEdges.BottomRight, HAlignment.Right, VAlignment.Bottom, CursorShape.NWSEResize);
        AddResizeHandle(MalinovLobbyTileEdges.TopRight, HAlignment.Right, VAlignment.Top, CursorShape.NESWResize);
        AddResizeHandle(MalinovLobbyTileEdges.BottomLeft, HAlignment.Left, VAlignment.Bottom, CursorShape.NESWResize);

        UpdateEditing();
    }

    /// <summary>
    /// Sets the header title; without a title the header shows only while editing.
    /// </summary>
    public void SetTitle(string title)
    {
        TitleLabel.Text = title;
        _hasTitle = !string.IsNullOrEmpty(title);
        UpdateEditing();
    }

    /// <summary>
    /// Shows <paramref name="context"/> in the tile's widget and lets the tile stand out when the widget asks for it.
    /// Content that is not a <see cref="IMalinovLobbyTileWidget"/> is left alone.
    /// </summary>
    public void Refresh(in MalinovLobbyTileContext context)
    {
        if (Content is not IMalinovLobbyTileWidget widget)
            return;

        widget.Refresh(context);
        Accented = widget.Accented;
    }

    /// <summary>
    /// Makes the tile transparent and fades it in after <paramref name="delay"/> seconds.
    /// </summary>
    public void FadeIn(float delay)
    {
        StopAnimation(FadeInKey);
        var transparent = Color.White.WithAlpha(0f);
        Modulate = transparent;

        var track = new AnimationTrackControlProperty
        {
            Property = nameof(Modulate),
            InterpolationMode = AnimationInterpolationMode.Linear,
        };
        track.KeyFrames.Add(new AnimationTrackProperty.KeyFrame(transparent, 0f));
        // A key of no length would divide by zero on a frame of no length.
        if (delay > 0f)
            track.KeyFrames.Add(new AnimationTrackProperty.KeyFrame(transparent, delay));
        track.KeyFrames.Add(new AnimationTrackProperty.KeyFrame(Color.White, FadeInSeconds, Easings.OutCubic));

        PlayAnimation(new Animation
        {
            Length = TimeSpan.FromSeconds(Math.Max(delay, 0f) + FadeInSeconds),
            AnimationTracks = { track },
        }, FadeInKey);
    }

    /// <summary>
    /// Moves <paramref name="content"/> into the tile, remembering its current parent.
    /// Content shown before is released first.
    /// </summary>
    public void Adopt(Control content)
    {
        Release();

        _origin = content.Parent;
        content.Orphan();
        ContentSlot.AddChild(content);
        Content = content;
    }

    /// <summary>
    /// Returns the content to the parent it was adopted from, or orphans it if it had none.
    /// </summary>
    public void Release()
    {
        if (Content == null)
            return;

        Content.Orphan();
        if (_origin is { Disposed: false })
            _origin.AddChild(Content);

        Content = null;
        _origin = null;
    }

    private void OnHeaderKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (!_editing || args.Function != EngineKeyFunctions.UIClick)
            return;

        DragPressed?.Invoke(this);
        args.Handle();
    }

    private void OnHeaderKeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (!_editing || args.Function != EngineKeyFunctions.UIClick)
            return;

        DragReleased?.Invoke(this);
        args.Handle();
    }

    /// <summary>
    /// Adds an invisible handle over the content that moves <paramref name="edges"/>; it lights up under the pointer.
    /// </summary>
    private void AddResizeHandle(MalinovLobbyTileEdges edges, HAlignment horizontal, VAlignment vertical, CursorShape cursor)
    {
        var corner = horizontal != HAlignment.Stretch && vertical != VAlignment.Stretch;
        var handle = new PanelContainer
        {
            HorizontalAlignment = horizontal,
            VerticalAlignment = vertical,
            MinWidth = corner ? CornerHandleSize : EdgeHandleThickness,
            MinHeight = corner ? CornerHandleSize : EdgeHandleThickness,
            MouseFilter = MouseFilterMode.Stop,
            DefaultCursorShape = cursor,
            Visible = false,
        };
        handle.AddStyleClass(StyleClassResizeHandle);

        handle.OnMouseEntered += _ => handle.AddStyleClass(StyleClassResizeHandleHovered);
        handle.OnMouseExited += _ => handle.RemoveStyleClass(StyleClassResizeHandleHovered);
        handle.OnKeyBindDown += args => OnResizeKeyBindDown(args, edges);
        handle.OnKeyBindUp += OnResizeKeyBindUp;

        AddChild(handle);
        _resizeHandles[edges] = handle;
    }

    private void OnResizeKeyBindDown(GUIBoundKeyEventArgs args, MalinovLobbyTileEdges edges)
    {
        if (!_editing || args.Function != EngineKeyFunctions.UIClick)
            return;

        ResizePressed?.Invoke(this, edges);
        args.Handle();
    }

    private void OnResizeKeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (!_editing || args.Function != EngineKeyFunctions.UIClick)
            return;

        ResizeReleased?.Invoke(this);
        args.Handle();
    }

    private void OnHidePressed(BaseButton.ButtonEventArgs args)
    {
        HidePressed?.Invoke(this);
    }

    private void UpdateEditing()
    {
        Header.Visible = _editing || _hasTitle;
        Header.MouseFilter = _editing ? MouseFilterMode.Stop : MouseFilterMode.Ignore;
        Header.DefaultCursorShape = _editing ? CursorShape.Move : CursorShape.Arrow;

        HideButton.Visible = _editing && _hideable;

        // A side is offered when the tile can change along it, a corner when it can change both ways.
        var widthChanges = _minTileSize.X != _maxTileSize.X;
        var heightChanges = _minTileSize.Y != _maxTileSize.Y;
        foreach (var (edges, handle) in _resizeHandles)
        {
            var horizontal = (edges & (MalinovLobbyTileEdges.Left | MalinovLobbyTileEdges.Right)) != 0;
            var vertical = (edges & (MalinovLobbyTileEdges.Top | MalinovLobbyTileEdges.Bottom)) != 0;
            handle.Visible = _editing && (!horizontal || widthChanges) && (!vertical || heightChanges);
        }
        HideButton.Text = _loc.GetString(_userHidden ? "malinov-lobby-tile-show-button" : "malinov-lobby-tile-hide-button");
        ContentSlot.Modulate = _editing && _userHidden ? Color.White.WithAlpha(FadedAlpha) : Color.White;
    }
}
