using System.Numerics;
using Content.Shared.Explosion;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.OptionButton;

namespace Content.Client.Administration.UI.SpawnExplosion;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class SpawnExplosionWindow : DefaultWindow
{
    [Dependency] private IClientConsoleHost _conHost = default!;
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entMan = default!;
    private readonly SharedMapSystem _mapSystem;
    private readonly SharedTransformSystem _transform = default!;

    private readonly SpawnExplosionEui _eui;
    private List<MapId> _mapData = new();
    private List<string> _explosionTypes = new();

    /// <summary>
    ///     Used to prevent unnecessary preview updates when setting fields (e.g., updating position)..
    /// </summary>
    private bool _pausePreview;

    public SpawnExplosionWindow(SpawnExplosionEui eui)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _mapSystem = _entMan.System<SharedMapSystem>();
        _transform = _entMan.System<TransformSystem>();
        _eui = eui;

        ExplosionOption.OnItemSelected += ExplosionSelected;
        MapOptions.OnItemSelected += MapSelected;
        Recentre.OnPressed += (_) => SetLocation();
        Spawn.OnPressed += SubmitButtonOnOnPressed;

        Preview.OnToggled += (_) => UpdatePreview();
        MapX.OnValueChanged += (_) => UpdatePreview();
        MapY.OnValueChanged += (_) => UpdatePreview();
        Intensity.OnValueChanged += (_) => UpdatePreview();
        Slope.OnValueChanged += (_) => UpdatePreview();
        MaxIntensity.OnValueChanged += (_) => UpdatePreview();
    }

    private void ExplosionSelected(ItemSelectedEventArgs args)
    {
        ExplosionOption.TrySelectId(args.Id); // Malinov-Edit: tolerate stale popup selections after a refresh.
        UpdatePreview();
    }

    private void MapSelected(ItemSelectedEventArgs args)
    {
        MapOptions.TrySelectId(args.Id); // Malinov-Edit: tolerate stale popup selections after a refresh.
        UpdatePreview();
    }

    protected override void EnteredTree()
    {
        UpdateExplosionTypeOptions();
        SetLocation(); // Malinov-Edit: populate explosion types before location callbacks can request a preview.
    }

    private void UpdateExplosionTypeOptions()
    {
        _explosionTypes.Clear();
        ExplosionOption.Clear();
        foreach (var type in _prototypeManager.EnumeratePrototypes<ExplosionPrototype>())
        {
            _explosionTypes.Add(type.ID);
            ExplosionOption.AddItem(type.ID);
        }
    }

    private void UpdateMapOptions()
    {
        _mapData.Clear();
        MapOptions.Clear();
        foreach (var map in _mapSystem.GetAllMapIds())
        {
            _mapData.Add(map);
            MapOptions.AddItem(map.ToString());
        }
    }

    /// <summary>
    ///     Set the current grid & indices based on the attached entities current location.
    /// </summary>
    private void SetLocation()
    {
        MalinovSetLocation(); // Malinov-Edit: allow nullspace and an empty map list.
    }

    private void UpdatePreview()
    {
        if (_pausePreview)
            return;

        // Malinov-Edit: validate refreshed selections and maps deleted while the window is open.
        var validSelection = MalinovUpdateSelection(out var mapId, out var explosionType);
        if (!Preview.Pressed || !validSelection)
        {
            _eui.ClearOverlay();
            return;
        }

        MapCoordinates coords = new(new Vector2(MapX.Value, MapY.Value), mapId);
        _eui.RequestPreviewData(coords, explosionType, Intensity.Value, Slope.Value, MaxIntensity.Value);
    }

    private void SubmitButtonOnOnPressed(ButtonEventArgs args)
    {
        // need to make room to view the fireworks
        Preview.Pressed = false;
        _eui.ClearOverlay();

        // for the actual explosion, we will just re-use the explosion command.
        // so assemble command arguments:
        // Malinov-Edit: do not submit stale or unavailable selections.
        if (!MalinovUpdateSelection(out var mapId, out var explosionType))
            return;
        var cmd = $"explosion {Intensity.Value} {Slope.Value} {MaxIntensity.Value} {MapX.Value} {MapY.Value} {mapId} {explosionType}";

        _conHost.ExecuteCommand(cmd);
    }
}
