blank_issues_enabled: true
contact_links:
  - name: Запросить функцию
    url: https://discord.gg/gN7mcJwNF
    about: Отправляйте запросы на добавление новых функций на нашем Discord сервере. (https://discord.gg/gN7mcJwNF).
