using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

/// <summary>
/// Quick-access picker for hair and facial hair markings, shown side by side directly on the
/// main appearance tab (mirrors how most SS14 forks surface hair/facial hair, e.g. Corvax's
/// SingleMarkingPicker) instead of requiring players to open the full markings tab for them.
/// Color editing for whichever marking is currently selected is shown in one shared area below
/// both pickers, rather than duplicated inside each one, with an option to drive both from a
/// single shared color.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HairMarkingsPicker : Control
{
    /// <summary>
    /// The layers shown by this picker. Also used by <see cref="MarkingPicker" /> to hide these
    /// layers from the general markings tab so they aren't editable in two places at once.
    /// </summary>
    public static readonly HumanoidVisualLayers[] Layers =
    {
        HumanoidVisualLayers.Hair,
        HumanoidVisualLayers.FacialHair,
    };

    // Facial hair marking names are almost all formatted as "Борода (X)" / "Beard (X)" (and the
    // moustache/sideburn equivalents) — that category word is redundant once the marking is
    // already shown under its own dedicated picker.
    private static readonly string[] FacialHairCategoryPrefixes =
    {
        "Борода ", "Beard ",
        "Усы ", "Moustache ",
        "Бакенбарды ", "Sideburns ",
    };

    [Dependency] private MarkingManager _marking = default!;

    private MarkingsViewModel? _markingsModel;
    private ProtoId<OrganCategoryPrototype>? _organ;
    private bool _syncColors;

    // The color sync is currently driving both layers with. Picking a new hair or facial hair
    // style would otherwise adopt that fresh marking's own random default color instead of
    // keeping whatever was already synced, so newly-selected markings are pulled onto this value
    // rather than onto whichever layer happened to just change. Cleared whenever sync turns off.
    private Color? _lastSyncedColor;

    // Set while writing a synced color to both layers, so the resulting MarkingsChanged events
    // don't reenter RefreshColors/ApplySyncedColor while we're already in the middle of it.
    private bool _applyingSyncedColor;

    // Tracks what ColorContent currently reflects, so color-only change events (which fire
    // through the same event as selection changes) don't tear down a slider mid-drag.
    private ProtoId<OrganCategoryPrototype>? _displayedOrgan;
    private ProtoId<MarkingPrototype>? _displayedHairId;
    private ProtoId<MarkingPrototype>? _displayedFacialHairId;
    private bool _displayedSynced;

    public HairMarkingsPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SyncColorsCheck.OnToggled += OnSyncColorsToggled;
    }

    public void SetModel(MarkingsViewModel model)
    {
        _markingsModel = model;
        UpdateMarkings();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        if (_markingsModel is null)
            return;

        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.OrganProfileDataChanged += OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
        _markingsModel.MarkingsChanged += OnMarkingsChanged;
        _markingsModel.MarkingsReset += RefreshColors;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        if (_markingsModel is null)
            return;

        _markingsModel.OrganDataChanged -= UpdateMarkings;
        _markingsModel.OrganProfileDataChanged -= OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged -= UpdateMarkings;
        _markingsModel.MarkingsChanged -= OnMarkingsChanged;
        _markingsModel.MarkingsReset -= RefreshColors;
    }

    private void OnOrganProfileDataChanged(bool refresh)
    {
        if (refresh)
            UpdateMarkings();
    }

    private void OnMarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        if (_applyingSyncedColor)
            return;

        if (_organ != organ || Array.IndexOf(Layers, layer) < 0)
            return;

        RefreshColors();
    }

    private void OnSyncColorsToggled(BaseButton.ButtonToggledEventArgs args)
    {
        _syncColors = args.Pressed;

        if (!_syncColors)
            _lastSyncedColor = null;

        RefreshColors();
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        Pickers.RemoveAllChildren();
        _organ = null;

        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            if (!_markingsModel.OrganProfileData.TryGetValue(organ, out var organProfileData))
                continue;

            foreach (var layer in Layers)
            {
                if (!organData.Layers.Contains(layer))
                    continue;

                // No facial hair marking is actually sex-restricted in the data, so female
                // characters would otherwise still see (and be able to grow) a beard — hide the
                // picker for them and clear out any facial hair already selected, e.g. from
                // switching sex after picking one as male.
                if (_markingsModel.EnforceGroupAndSexRestrictions
                    && layer == HumanoidVisualLayers.FacialHair
                    && organProfileData.Sex == Sex.Female)
                {
                    ClearLayer(organ, layer);
                    continue;
                }

                var allMarkings = _markingsModel.EnforceGroupAndSexRestrictions
                    ? _marking.MarkingsByLayerAndGroupAndSex(layer, organData.Group, organProfileData.Sex)
                    : _marking.MarkingsByLayer(layer);

                if (allMarkings.Count == 0)
                    continue;

                _organ = organ;

                var column = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                };
                column.AddChild(new Label
                {
                    Text = Loc.GetString($"markings-layer-{layer}"),
                    StyleClasses = { StyleClass.LabelHeading },
                });
                column.AddChild(new LayerMarkingPicker(
                    _markingsModel,
                    organ,
                    layer,
                    allMarkings,
                    showSelectedPanel: false,
                    showStatusLabel: false,
                    itemNameOverride: layer == HumanoidVisualLayers.FacialHair ? StripFacialHairCategory : null)
                {
                    MinSize = new Vector2(0, 480),
                    VerticalExpand = true,
                });

                Pickers.AddChild(column);
            }

            // Hair and facial hair are always defined on the same organ (the head).
            if (_organ is not null)
                break;
        }

        Visible = Pickers.ChildCount > 0;
        RefreshColors();
    }

    private void RefreshColors()
    {
        Marking? hair = null;
        Marking? facialHair = null;

        if (_markingsModel is not null && _organ is { } organ)
        {
            hair = FirstSelected(organ, HumanoidVisualLayers.Hair);
            facialHair = FirstSelected(organ, HumanoidVisualLayers.FacialHair);
        }

        // Both hair and facial hair are optional, so it's normal to pass through a state where
        // only one of them is chosen while browsing styles. Turn sync back off the moment either
        // is removed instead of just pausing it — auto-resuming it later would silently reapply
        // the old remembered color over whatever was deliberately set on the remaining layer
        // while the other was gone.
        var bothSelected = hair is not null && facialHair is not null;
        if (!bothSelected && _syncColors)
        {
            _syncColors = false;
            SyncColorsCheck.Pressed = false;
            _lastSyncedColor = null;
        }

        var hairId = hair?.MarkingId;
        var facialHairId = facialHair?.MarkingId;
        var selectionChanged = _organ != _displayedOrgan || hairId != _displayedHairId || facialHairId != _displayedFacialHairId;
        var modeChanged = _syncColors != _displayedSynced;

        // Color changes are reported through the same event as selection changes, and this method
        // is called in reaction to both. Rebuilding on every color tweak would tear down the very
        // slider the user is dragging mid-gesture, so only rebuild when the selected marking (or
        // sync mode) actually changed — a color-only change leaves the sliders alone.
        if (!selectionChanged && !modeChanged)
            return;

        // A newly-picked hair/facial hair marking starts out with its own independent default
        // color. Pull it onto the color sync was already using — not onto whichever layer just
        // happened to change — so picking a new style never "resets" the color you'd set.
        if (_syncColors && _organ is { } syncOrgan)
        {
            var syncColor = _lastSyncedColor;
            if (syncColor is null && (hair ?? facialHair) is { } initial && initial.MarkingColors.Count > 0)
                syncColor = initial.MarkingColors[0];

            if (syncColor is { } color)
            {
                ApplySyncedColor(syncOrgan, color, hair, facialHair);
                hair = FirstSelected(syncOrgan, HumanoidVisualLayers.Hair);
                facialHair = FirstSelected(syncOrgan, HumanoidVisualLayers.FacialHair);
            }
        }

        _displayedOrgan = _organ;
        _displayedHairId = hairId;
        _displayedFacialHairId = facialHairId;
        _displayedSynced = _syncColors;

        ColorContent.RemoveAllChildren();
        SyncColorsCheck.Visible = bothSelected;

        if (_organ is not { } currentOrgan || (hair is null && facialHair is null))
        {
            ColorSection.Visible = false;
            return;
        }

        ColorSection.Visible = true;

        if (_syncColors)
        {
            RefreshSyncedColors(currentOrgan, hair, facialHair);
            return;
        }

        foreach (var (layer, marking) in new[] { (HumanoidVisualLayers.Hair, hair), (HumanoidVisualLayers.FacialHair, facialHair) })
        {
            if (marking is not { } selected)
                continue;

            if (!_marking.TryGetMarking(selected, out var markingProto))
                continue;

            var column = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };
            LayerMarkingPicker.PopulateColorSliders(_markingsModel!, currentOrgan, layer, column, selected.MarkingId, markingProto, selected.MarkingColors, showSpriteLabels: false);
            ColorContent.AddChild(column);
        }
    }

    private void RefreshSyncedColors(ProtoId<OrganCategoryPrototype> organ, Marking? hair, Marking? facialHair)
    {
        var source = hair ?? facialHair;

        if (source is not { } marking || marking.MarkingColors.Count == 0)
            return;

        var selector = new ColorSelectorSliders
        {
            SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv,
            Color = marking.MarkingColors[0],
        };
        selector.OnColorChanged += _ => ApplySyncedColor(organ, selector.Color, hair, facialHair);

        var column = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        column.AddChild(selector);
        ColorContent.AddChild(column);
    }

    private void ApplySyncedColor(ProtoId<OrganCategoryPrototype> organ, Color color, Marking? hair, Marking? facialHair)
    {
        if (_markingsModel is null)
            return;

        _lastSyncedColor = color;

        _applyingSyncedColor = true;
        try
        {
            if (hair is { } h)
                _markingsModel.TrySetMarkingColor(organ, HumanoidVisualLayers.Hair, h.MarkingId, 0, color);

            if (facialHair is { } f)
                _markingsModel.TrySetMarkingColor(organ, HumanoidVisualLayers.FacialHair, f.MarkingId, 0, color);
        }
        finally
        {
            _applyingSyncedColor = false;
        }
    }

    private Marking? FirstSelected(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        var markings = _markingsModel?.SelectedMarkings(organ, layer);
        return markings is { Count: > 0 } ? markings[0] : null;
    }

    private void ClearLayer(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        var markings = _markingsModel?.SelectedMarkings(organ, layer);
        if (markings is not { Count: > 0 })
            return;

        // Snapshot first — TryDeselectMarking mutates the same list this would otherwise enumerate.
        foreach (var marking in markings.ToArray())
            _markingsModel!.TryDeselectMarking(organ, layer, marking.MarkingId);
    }

    private static string StripFacialHairCategory(string name)
    {
        foreach (var prefix in FacialHairCategoryPrefixes)
        {
            if (!name.StartsWith(prefix, StringComparison.Ordinal))
                continue;

            var rest = name[prefix.Length..].Trim();
            if (rest.Length >= 2 && rest[0] == '(' && rest[^1] == ')')
                return rest[1..^1];
        }

        return name;
    }
}
