using System.Linq;
using Content.Client.Guidebook.Controls;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class LayerMarkingItem : BoxContainer, ISearchableControl
{
    [Dependency] private IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;

    private readonly MarkingsViewModel _markingsModel;
    private readonly MarkingPrototype _markingPrototype;
    private readonly ProtoId<OrganCategoryPrototype> _organ;
    private readonly HumanoidVisualLayers _layer;
    private bool _interactive;

    public event Action<GUIBoundKeyEventArgs, LayerMarkingItem>? Pressed;
    public event Action<GUIBoundKeyEventArgs, LayerMarkingItem>? Unpressed;
    public event Action<LayerMarkingItem, bool>? OnToggled;
    public ProtoId<MarkingPrototype> MarkingId => _markingPrototype.ID;

    public LayerMarkingItem(MarkingsViewModel model, ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer, MarkingPrototype prototype, bool interactive)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        _markingsModel = model;
        _markingPrototype = prototype;
        _organ = organ;
        _layer = layer;
        _interactive = interactive;

        UpdateData();
        UpdateSelection();

        SelectButton.OnPressed += SelectButtonPressed;

        OnKeyBindDown += OnPressed;
        OnKeyBindUp += OnUnpressed;

        if (!interactive)
        {
            SelectButton.MouseFilter = Control.MouseFilterMode.Ignore;
        }
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.MarkingsReset += UpdateSelection;
        _markingsModel.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.MarkingsReset -= UpdateSelection;
        _markingsModel.MarkingsChanged -= MarkingsChanged;
    }

    private void MarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        if (_organ != organ || _layer != layer)
            return;

        UpdateSelection();
    }

    private void UpdateData()
    {
        MarkingTexture.Textures = _markingPrototype.Sprites.Select(layer => _sprite.Frame0(layer)).ToList();
        SelectButton.Text = Loc.GetString($"marking-{_markingPrototype.ID}");
    }

    /// <summary>
    /// Resyncs the visual pressed state of the select button with the actual selection state in the model.
    /// </summary>
    public void UpdateSelection()
    {
        var selected = _markingsModel.IsMarkingSelected(_organ, _layer, _markingPrototype.ID);
        SelectButton.Pressed = selected && _interactive;
    }

    private void SelectButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (!_interactive)
        {
            SelectButton.Pressed = false;
            return;
        }

        OnToggled?.Invoke(this, SelectButton.Pressed);
    }

    public bool CheckMatchesSearch(string query)
    {
        return Loc.GetString($"marking-{_markingPrototype.ID}").Contains(query, StringComparison.OrdinalIgnoreCase);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    private void OnPressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Pressed?.Invoke(args, this);
    }

    private void OnUnpressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Unpressed?.Invoke(args, this);
    }
}
