using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.Guidebook.Controls;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class LayerMarkingPicker : BoxContainer
{
    [Dependency] private IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;

    private readonly IReadOnlyDictionary<string, MarkingPrototype> _allMarkings;
    private readonly ProtoId<OrganCategoryPrototype> _organ;
    private readonly HumanoidVisualLayers _layer;
    private readonly MarkingsViewModel _markingsModel;
    private List<ISearchableControl> _searchable = new();

    private readonly Dictionary<ProtoId<MarkingPrototype>, BoxContainer> _selectedEntries = new();
    private readonly Dictionary<ProtoId<MarkingPrototype>, BoxContainer> _selectedColorContainers = new();
    private ProtoId<MarkingPrototype>? _activeColorEntry;

    private readonly Func<string, string>? _itemNameOverride;

    public LayerMarkingPicker(MarkingsViewModel markingsModel, ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer, IReadOnlyDictionary<string, MarkingPrototype> allMarkings, bool showSelectedPanel = true, bool showStatusLabel = true, Func<string, string>? itemNameOverride = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        _markingsModel = markingsModel;
        _allMarkings = allMarkings;
        _organ = organ;
        _layer = layer;
        _itemNameOverride = itemNameOverride;

        SelectedPanel.Visible = showSelectedPanel;
        MarkingsStatus.Visible = showStatusLabel;

        UpdateMarkings();

        SearchBar.OnTextChanged += _ =>
        {
            foreach (var element in _searchable)
            {
                element.SetHiddenState(true, SearchBar.Text.Trim());
            }
        };

        UpdateCount();
        // Seed the "Selected" panel with any markings that are already selected in the model
        // (e.g. loaded from a saved profile) instead of only ever adding to it on user interaction.
        RefreshSelectedList();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.MarkingsReset += OnMarkingsReset;
        _markingsModel.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.MarkingsReset -= OnMarkingsReset;
        _markingsModel.MarkingsChanged -= MarkingsChanged;
    }

    private void OnMarkingsReset()
    {
        UpdateCount();
        RefreshSelectedList();
    }

    private void MarkingsChanged(ProtoId<OrganCategoryPrototype> organ, HumanoidVisualLayers layer)
    {
        if (_organ != organ || _layer != layer)
            return;

        UpdateCount();
        RefreshSelectedList();
    }

    private void RefreshSelectedList()
    {
        var stillSelected = new HashSet<ProtoId<MarkingPrototype>>();
        foreach (var marking in _markingsModel.SelectedMarkings(_organ, _layer) ?? Enumerable.Empty<Marking>())
        {
            stillSelected.Add(marking.MarkingId);
            AddSelectedEntry(marking.MarkingId);
        }

        foreach (var (markingId, _) in _selectedEntries.ToArray())
        {
            if (!stillSelected.Contains(markingId))
                RemoveSelectedEntry(markingId);
        }
    }

    private void UpdateMarkings()
    {
        foreach (var marking in _allMarkings.Values.OrderBy(marking => Loc.GetString($"marking-{marking.ID}")))
        {
            var item = new LayerMarkingItem(_markingsModel, _organ, _layer, marking, true, _itemNameOverride);
            item.OnToggled += OnItemToggled;
            Items.AddChild(item);
        }
        _searchable = Items.GetSearchableControls();
    }

    private void UpdateCount()
    {
        _markingsModel.GetMarkingCounts(_organ, _layer, out var isRequired, out var count, out var selected);
        MarkingsStatus.Text = Loc.GetString("markings-limits", ("required", isRequired), ("count", count), ("selectable", count - selected));
    }

    private void OnItemToggled(LayerMarkingItem item, bool selected)
    {
        if (selected)
        {
            if (!_markingsModel.TrySelectMarking(_organ, _layer, item.MarkingId))
            {
                // Selection was rejected (e.g. the layer's selection limit was reached),
                // so revert the button's visual state instead of leaving it highlighted as selected.
                item.UpdateSelection();
                return;
            }

            AddSelectedEntry(item.MarkingId);
        }
        else
        {
            if (!_markingsModel.TryDeselectMarking(_organ, _layer, item.MarkingId))
            {
                item.UpdateSelection();
                return;
            }

            RemoveSelectedEntry(item.MarkingId);
        }
    }

    private void AddSelectedEntry(ProtoId<MarkingPrototype> markingId)
    {
        if (_selectedEntries.ContainsKey(markingId))
            return;

        var colorContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            Margin = new Thickness(8, 0, 0, 0),
        };

        var headerRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        if (_allMarkings.TryGetValue(markingId, out var markingProto))
        {
            var iconPanel = new PanelContainer
            {
                SetSize = new Vector2(64, 64),
                MouseFilter = MouseFilterMode.Ignore,
            };
            iconPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1B1B1E") };
            iconPanel.AddChild(new LayeredTextureRect
            {
                TextureScale = new Vector2(2, 2),
                Textures = markingProto.Sprites.Select(sprite => _sprite.Frame0(sprite)).ToList(),
            });

            headerRow.AddChild(iconPanel);
        }

        var header = new Button
        {
            Text = Loc.GetString($"marking-{markingId}"),
            HorizontalExpand = true,
            ToggleMode = true,
        };
        header.OnPressed += _ => OnSelectedEntryPressed(markingId);
        headerRow.AddChild(header);

        var container = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        container.AddChild(headerRow);
        container.AddChild(colorContainer);

        SelectedList.AddChild(container);
        _selectedEntries[markingId] = container;
        _selectedColorContainers[markingId] = colorContainer;
    }

    private void RemoveSelectedEntry(ProtoId<MarkingPrototype> markingId)
    {
        if (!_selectedEntries.TryGetValue(markingId, out var container))
            return;

        SelectedList.RemoveChild(container);
        _selectedEntries.Remove(markingId);
        _selectedColorContainers.Remove(markingId);

        if (_activeColorEntry == markingId)
        {
            _activeColorEntry = null;
        }
    }

    private void OnSelectedEntryPressed(ProtoId<MarkingPrototype> markingId)
    {
        if (_activeColorEntry.HasValue && _activeColorEntry.Value != markingId)
        {
            if (_selectedColorContainers.TryGetValue(_activeColorEntry.Value, out var prevContainer))
            {
                prevContainer.Visible = false;
            }
        }

        if (_activeColorEntry == markingId)
        {
            if (_selectedColorContainers.TryGetValue(markingId, out var prev))
                prev.Visible = false;
            _activeColorEntry = null;
            return;
        }

        _activeColorEntry = markingId;

        if (!_selectedColorContainers.TryGetValue(markingId, out var colorContainer))
            return;

        if (colorContainer.ChildCount > 0)
        {
            colorContainer.Visible = true;
            return;
        }

        if (_markingsModel.GetMarking(_organ, _layer, markingId) is not { } marking)
            return;

        if (!_allMarkings.TryGetValue(markingId, out var markingProto))
            return;

        PopulateColorSliders(_markingsModel, _organ, _layer, colorContainer, markingId, markingProto, marking.MarkingColors);

        colorContainer.Visible = true;
    }

    /// <summary>
    /// Builds a column of per-sprite color sliders for a marking into <paramref name="container" />,
    /// wired to write changes back into <paramref name="markingsModel" />.
    /// </summary>
    public static void PopulateColorSliders(
        MarkingsViewModel markingsModel,
        ProtoId<OrganCategoryPrototype> organ,
        HumanoidVisualLayers layer,
        BoxContainer container,
        ProtoId<MarkingPrototype> markingId,
        MarkingPrototype markingProto,
        IReadOnlyList<Color> colors,
        bool showSpriteLabels = true)
    {
        for (var i = 0; i < markingProto.Sprites.Count; i++)
        {
            var sliderContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            container.AddChild(sliderContainer);

            var selector = new ColorSelectorSliders();
            selector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;

            if (showSpriteLabels)
            {
                // Falls back to the raw, untranslated locale key (e.g. an RSI state name) when no
                // per-sprite label is defined, which is only meaningful when a marking has more
                // than one sprite/color — callers with a single-sprite marking should pass false.
                var label = markingProto.Sprites[i] switch
                {
                    SpriteSpecifier.Rsi rsi => Loc.GetString($"marking-{markingId}-{rsi.RsiState}"),
                    SpriteSpecifier.Texture texture => Loc.GetString($"marking-{markingId}-{texture.TexturePath.Filename}"),
                    _ => throw new InvalidOperationException("SpriteSpecifier not of known type"),
                };

                sliderContainer.AddChild(new Label { Text = label });
            }

            sliderContainer.AddChild(selector);

            selector.Color = colors[i];

            var colorIndex = i;
            selector.OnColorChanged += _ =>
            {
                markingsModel.TrySetMarkingColor(organ, layer, markingId, colorIndex, selector.Color);
            };
        }
    }
}
