using System.Linq;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    // Organs grouped under a single organ-selector entry (with sub-tabs per organ), the same way
    // the head's several layers are shown as sub-tabs under one entry, instead of one entry per organ.
    private static readonly (string LocKey, ProtoId<OrganCategoryPrototype>[] Organs)[] OrganGroups =
    {
        ("markings-organ-group-arms", new ProtoId<OrganCategoryPrototype>[] { "ArmLeft", "ArmRight", "HandLeft", "HandRight" }),
        ("markings-organ-group-legs", new ProtoId<OrganCategoryPrototype>[] { "LegLeft", "LegRight", "FootLeft", "FootRight" }),
    };

    private MarkingsViewModel? _markingsModel;
    private readonly Dictionary<int, Control> _organPickers = new();

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        OrganSelector.OnItemSelected += args =>
        {
            OrganSelector.SelectId(args.Id);

            foreach (var (_, picker) in _organPickers)
                picker.Visible = false;
            if (_organPickers.TryGetValue(args.Id, out var selected))
                selected.Visible = true;
        };
    }

    public void SetModel(MarkingsViewModel model)
    {
        _markingsModel = model;

        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel?.OrganDataChanged += UpdateMarkings;
        _markingsModel?.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel?.OrganDataChanged -= UpdateMarkings;
        _markingsModel?.EnforcementsChanged -= UpdateMarkings;
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        OrganSelector.Clear();
        OrganPanel.RemoveAllChildren();
        _organPickers.Clear();

        var i = 0;
        var groupedOrgans = new HashSet<ProtoId<OrganCategoryPrototype>>();

        foreach (var (locKey, organs) in OrganGroups)
        {
            var entries = new List<(ProtoId<OrganCategoryPrototype>, HumanoidVisualLayers, ProtoId<MarkingsGroupPrototype>)>();

            foreach (var organ in organs)
            {
                if (!_markingsModel.OrganData.TryGetValue(organ, out var organData))
                    continue;

                groupedOrgans.Add(organ);

                // Hair and facial hair have their own dedicated quick pickers on the appearance
                // tab, so they're hidden here to avoid editing the same markings in two places.
                foreach (var layer in organData.Layers)
                {
                    if (HairMarkingsPicker.Layers.Contains(layer))
                        continue;

                    entries.Add((organ, layer, organData.Group));
                }
            }

            if (entries.Count == 0)
                continue;

            var groupControl = new OrganGroupMarkingPicker(_markingsModel, entries);
            if (groupControl.Empty)
                continue;

            OrganSelector.AddItem(Loc.GetString(locKey), i);
            groupControl.Visible = false;
            OrganPanel.AddChild(groupControl);
            _organPickers[i] = groupControl;
            i++;
        }

        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            if (groupedOrgans.Contains(organ))
                continue;

            var layers = new HashSet<HumanoidVisualLayers>(organData.Layers);
            layers.ExceptWith(HairMarkingsPicker.Layers);

            // Tail and Special aren't meant to be user-editable markings on the torso.
            if (organ == "Torso")
                layers.ExceptWith(new[] { HumanoidVisualLayers.Tail, HumanoidVisualLayers.Special });

            if (layers.Count == 0)
                continue;

            var control = new OrganMarkingPicker(_markingsModel, organ, layers, organData.Group);
            if (control.Empty)
                continue;

            OrganSelector.AddItem(Loc.GetString($"markings-organ-{organ.Id}"), i);
            control.Visible = false;
            OrganPanel.AddChild(control);
            _organPickers[i] = control;
            i++;
        }

        if (i > 0)
        {
            OrganSelector.SelectId(0);
            _organPickers[0].Visible = true;
        }

        OrganSelector.Visible = i > 1;
    }
}
