using System.Linq;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    private MarkingsViewModel? _markingsModel;
    private readonly Dictionary<int, OrganMarkingPicker> _organPickers = new();

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        OrganSelector.OnItemSelected += args =>
        {
            OrganSelector.SelectId(args.Id);

            foreach (var (_, picker) in _organPickers)
                picker.Visible = false;
            if (_organPickers.TryGetValue(args.Id, out var selected))
                selected.Visible = true;
        };
    }

    public void SetModel(MarkingsViewModel model)
    {
        _markingsModel = model;

        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel?.OrganDataChanged += UpdateMarkings;
        _markingsModel?.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel?.OrganDataChanged -= UpdateMarkings;
        _markingsModel?.EnforcementsChanged -= UpdateMarkings;
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        OrganSelector.Clear();
        OrganPanel.RemoveAllChildren();
        _organPickers.Clear();

        var i = 0;
        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            // Hair and facial hair have their own dedicated quick pickers on the appearance tab,
            // so they're hidden here to avoid editing the same markings in two different places.
            var layers = new HashSet<HumanoidVisualLayers>(organData.Layers);
            layers.ExceptWith(HairMarkingsPicker.Layers);

            if (layers.Count == 0)
                continue;

            var control = new OrganMarkingPicker(_markingsModel, organ, layers, organData.Group);
            if (control.Empty)
                continue;

            OrganSelector.AddItem(Loc.GetString($"markings-organ-{organ.Id}"), i);
            control.Visible = false;
            OrganPanel.AddChild(control);
            _organPickers[i] = control;
            i++;
        }

        if (i > 0)
        {
            OrganSelector.SelectId(0);
            _organPickers[0].Visible = true;
        }

        OrganSelector.Visible = i > 1;
    }
}
