using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

/// <summary>
/// Groups markings from several distinct organs (e.g. both arms and both hands) under one set of
/// tabs, the same way <see cref="OrganMarkingPicker" /> groups several layers of a single organ —
/// used to present a set of related limbs as one entry in the organ selector instead of one per organ.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OrganGroupMarkingPicker : Control
{
    [Dependency] private MarkingManager _marking = default!;

    private readonly MarkingsViewModel _markingsModel;
    private readonly List<(ProtoId<OrganCategoryPrototype> Organ, HumanoidVisualLayers Layer, ProtoId<MarkingsGroupPrototype> Group)> _entries;

    public OrganGroupMarkingPicker(
        MarkingsViewModel markingsModel,
        List<(ProtoId<OrganCategoryPrototype> Organ, HumanoidVisualLayers Layer, ProtoId<MarkingsGroupPrototype> Group)> entries)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _markingsModel = markingsModel;
        _entries = entries;

        UpdateMarkings();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.OrganProfileDataChanged += OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.OrganProfileDataChanged -= OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged -= UpdateMarkings;
    }

    public bool Empty => LayerTabs.ChildCount == 0;

    private void OnOrganProfileDataChanged(bool refresh)
    {
        if (refresh)
            UpdateMarkings();
    }

    private void UpdateMarkings()
    {
        LayerTabs.RemoveAllChildren();
        var i = 0;

        foreach (var (organ, layer, group) in _entries)
        {
            if (!_markingsModel.OrganProfileData.TryGetValue(organ, out var organProfileData))
                continue;

            var allMarkings = _markingsModel.EnforceGroupAndSexRestrictions
                ? _marking.MarkingsByLayerAndGroupAndSex(layer, group, organProfileData.Sex)
                : _marking.MarkingsByLayer(layer);

            if (allMarkings.Count == 0)
                continue;

            var control = new LayerMarkingPicker(_markingsModel, organ, layer, allMarkings);
            LayerTabs.AddChild(control);
            if (Loc.TryGetString($"markings-layer-{layer}-{group.Id}", out var layerTitle))
                LayerTabs.SetTabTitle(i, layerTitle);
            else if (Loc.TryGetString($"markings-organ-{organ.Id}", out var organTitle))
                LayerTabs.SetTabTitle(i, organTitle);
            else
                LayerTabs.SetTabTitle(i, Loc.GetString($"markings-layer-{layer}"));
            i++;
        }

        LayerTabs.TabsVisible = i > 1;
    }
}
