using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            // Malinov edit start - song credits live in the credits lobby tile (MalinovCreditsTileWidget)
            // LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            // Malinov edit end

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            // Malinov edit start - the collapsible right panel is gone, lobby tiles replace it
            // CollapseButton.OnPressed += _ => TogglePanel(false);
            // ExpandButton.OnPressed += _ => TogglePanel(true);
            // Malinov edit end
        }

        public void SwitchState(LobbyGuiState state)
        {
            // Malinov edit start - the tile grid replaces DefaultState and RightSide
            TileHost.Visible = false;
            CharacterSetupState.Visible = false;
            // Malinov edit end

            switch (state)
            {
                case LobbyGuiState.Default:
                    TileHost.Visible = true; // Malinov-Edit
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    // Malinov edit start - character setup takes the whole screen
                    // var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    // var setupWidth = (float) LeftSide.PixelWidth;
                    //
                    // if (1 - (setupWidth / actualWidth) > 0.30)
                    // {
                    //     RightSide.Visible = false;
                    // }
                    // Malinov edit end

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        // Malinov edit start - the collapsible right panel is gone, lobby tiles replace it
        // private void TogglePanel(bool value)
        // {
        //     RightSide.Visible = value;
        //     ExpandPanel.Visible = !value;
        // }
        // Malinov edit end

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
