using System.Linq;
using Content.Client.Lathe.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._MalinovStation.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._MalinovStation.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : FancyWindow
{
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private readonly SurgerySystem _system;

    public event Action<ProtoId<SurgeryPrototype>, ProtoId<SurgeryStepPrototype>>? OnStepChosen;

    private EntityUid _patient;
    private List<SurgeryDisplay> _surgeries = new();
    private ProtoId<SurgeryRegionPrototype>? _selectedRegion;
    private ProtoId<SurgeryPrototype>? _selectedSurgery;
    private ViewType _view = ViewType.Regions;

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entities.System<SurgerySystem>();

        RegionsButton.OnPressed += _ => SetView(ViewType.Regions);
        SurgeriesButton.OnPressed += _ => SetView(ViewType.Surgeries);
        StepsButton.OnPressed += _ => SetView(ViewType.Steps);
    }

    public void SetPatient(EntityUid patient)
    {
        _patient = patient;
    }

    public void Populate(SurgeryBuiState state)
    {
        _surgeries = state.Surgeries;

        if (_selectedSurgery is { } sel && _surgeries.All(s => s.Surgery != sel))
            _selectedSurgery = null;

        if (_selectedRegion is { } region && !GetRegions().Contains(region))
            _selectedRegion = null;

        if (_selectedRegion == null && _view != ViewType.Regions)
            _view = ViewType.Regions;
        else if (_selectedSurgery == null && _view == ViewType.Steps)
            _view = ViewType.Surgeries;

        RebuildRegions();
        RebuildSurgeries();
        RebuildSteps();
        SetView(_view);
    }

    /// <summary>
    /// Re-checks whether the currently-selected step can actually be performed right now (held tools,
    /// posture) using the local player - called live as the player swaps items in/out of their hands,
    /// without waiting on a server round-trip.
    /// </summary>
    public void RefreshValidity()
    {
        RebuildSteps();
        UpdateDisabledPanel();
    }

    /// <summary>Distinct regions actually represented by the surgeries currently on offer.</summary>
    private List<ProtoId<SurgeryRegionPrototype>> GetRegions()
    {
        var regions = new List<ProtoId<SurgeryRegionPrototype>>();

        foreach (var surgery in _surgeries)
        {
            if (_proto.TryIndex(surgery.Surgery, out var proto) && !regions.Contains(proto.Region))
                regions.Add(proto.Region);
        }

        return regions;
    }

    private void RebuildRegions()
    {
        RegionList.DisposeAllChildren();

        var regions = new List<(ProtoId<SurgeryRegionPrototype> Id, SurgeryRegionPrototype Proto)>();
        foreach (var regionId in GetRegions())
        {
            if (_proto.TryIndex(regionId, out var regionProto))
                regions.Add((regionId, regionProto));
        }

        regions.Sort((a, b) => a.Proto.SortOrder.CompareTo(b.Proto.SortOrder));

        foreach (var (id, proto) in regions)
        {
            var button = new Button
            {
                Text = Loc.GetString(proto.Name),
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
            };

            button.OnPressed += _ =>
            {
                _selectedRegion = id;
                _selectedSurgery = null;
                RebuildSurgeries();
                RebuildSteps();
                SetView(ViewType.Surgeries);
            };

            RegionList.AddChild(button);
        }

        if (regions.Count == 0)
        {
            RegionList.AddChild(new Label
            {
                Text = Loc.GetString("surgery-window-no-surgeries"),
                HorizontalAlignment = HAlignment.Center,
                StyleClasses = { "LabelSubText" },
            });
        }
    }

    private void RebuildSurgeries()
    {
        SurgeryList.DisposeAllChildren();

        foreach (var surgery in _surgeries)
        {
            if (!_proto.TryIndex(surgery.Surgery, out var proto) || proto.Region != _selectedRegion)
                continue;

            // A surgery disappears from the list entirely once its last step completes (see
            // SurgerySystem.GetSurgeriesToShow), so the only distinguishable state here is
            // "not yet started" vs "partway through" - tint the latter to make it stand out.
            var inProgress = surgery.Steps.Any(s => s.Status == SurgeryStepStatus.Completed);

            var button = new Button
            {
                Text = Loc.GetString(proto.Name),
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
            };

            if (inProgress)
                button.Modulate = Color.Orange;

            var id = surgery.Surgery;
            button.OnPressed += _ =>
            {
                _selectedSurgery = id;
                RebuildSteps();
                SetView(ViewType.Steps);
            };

            SurgeryList.AddChild(button);
        }
    }

    private void RebuildSteps()
    {
        StepList.DisposeAllChildren();

        var surgery = _surgeries.FirstOrDefault(s => s.Surgery == _selectedSurgery);
        if (surgery == null || !_proto.TryIndex(surgery.Surgery, out var surgeryProto))
            return;

        var localUser = _player.LocalEntity;

        foreach (var step in surgery.Steps)
        {
            if (!_proto.TryIndex(step.Step, out var proto))
                continue;

            var status = step.Status;
            string? tooltip = proto.Description is { } desc ? Loc.GetString(desc) : null;
            var disabled = status != SurgeryStepStatus.Available;

            // The server only knows step order (Locked/Available/Completed). For the one step that's
            // actually next, ask the shared system - using our own held items - whether it's really
            // performable right now, same logic the server itself gates the DoAfter with.
            if (status == SurgeryStepStatus.Available && localUser is { } user &&
                !_system.TryValidateStep(user, _patient, surgeryProto, proto, out _, out var reason))
            {
                disabled = true;
                if (reason != null)
                    tooltip = Loc.GetString(reason);
            }

            var button = new Button
            {
                Text = Loc.GetString(proto.Name),
                HorizontalExpand = true,
                Disabled = disabled,
                Margin = new Thickness(0, 0, 0, 2),
            };

            button.Modulate = status switch
            {
                SurgeryStepStatus.Completed => Color.LimeGreen,
                SurgeryStepStatus.Locked => Color.Gray,
                _ when disabled => Color.IndianRed,
                _ => Color.White,
            };

            if (tooltip != null)
            {
                var tooltipText = tooltip;
                button.TooltipSupplier = _ => new RecipeTooltip(tooltipText);
            }

            var surgeryId = surgery.Surgery;
            var stepId = step.Step;
            button.OnPressed += _ => OnStepChosen?.Invoke(surgeryId, stepId);

            StepList.AddChild(button);
        }
    }

    private void UpdateDisabledPanel()
    {
        if (_patient == default || !_entities.EntityExists(_patient) || _system.IsLyingDown(_patient))
        {
            DisabledPanel.Visible = false;
            DisabledPanel.MouseFilter = MouseFilterMode.Ignore;
            return;
        }

        DisabledPanel.Visible = true;
        DisabledPanel.MouseFilter = MouseFilterMode.Stop;

        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("surgery-window-needs-lying-down"));
        DisabledLabel.SetMessage(msg);
    }

    private void SetView(ViewType view)
    {
        _view = view;

        RegionList.Visible = view == ViewType.Regions;
        RegionsButton.Disabled = view == ViewType.Regions;

        SurgeryList.Visible = view == ViewType.Surgeries;
        SurgeriesButton.Disabled = view == ViewType.Surgeries || _selectedRegion == null;

        StepList.Visible = view == ViewType.Steps;
        StepsButton.Disabled = view == ViewType.Steps || _selectedSurgery == null;

        Title = BuildTitle();
        UpdateDisabledPanel();
    }

    private string BuildTitle()
    {
        if (_selectedSurgery is { } surgeryId && _proto.TryIndex(surgeryId, out var surgeryProto))
            return Loc.GetString("surgery-window-title-with-surgery", ("surgery", Loc.GetString(surgeryProto.Name)));

        if (_selectedRegion is { } regionId && _proto.TryIndex(regionId, out var regionProto))
            return Loc.GetString("surgery-window-title-with-region", ("region", Loc.GetString(regionProto.Name)));

        return Loc.GetString("surgery-window-title");
    }

    private enum ViewType
    {
        Regions,
        Surgeries,
        Steps,
    }
}
