using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._MalinovStation.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._MalinovStation.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;

    public event Action<ProtoId<SurgeryPrototype>, ProtoId<SurgeryStepPrototype>>? OnStepChosen;

    private List<SurgeryDisplay> _surgeries = new();
    private ProtoId<SurgeryPrototype>? _selected;

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(SurgeryBuiState state)
    {
        _surgeries = state.Surgeries;

        if (_selected is { } sel && _surgeries.All(s => s.Surgery != sel))
            _selected = null;

        RebuildSurgeries();
        RebuildSteps();
    }

    private void RebuildSurgeries()
    {
        SurgeryList.DisposeAllChildren();

        foreach (var surgery in _surgeries)
        {
            if (!_proto.TryIndex(surgery.Surgery, out var proto))
                continue;

            var isSelected = surgery.Surgery == _selected;
            var button = new Button
            {
                Text = Loc.GetString(proto.Name),
                Modulate = isSelected ? Color.LightSkyBlue : Color.White,
            };

            var id = surgery.Surgery;
            button.OnPressed += _ =>
            {
                _selected = id;
                RebuildSurgeries();
                RebuildSteps();
            };

            SurgeryList.AddChild(button);
        }
    }

    private void RebuildSteps()
    {
        StepList.DisposeAllChildren();

        var surgery = _surgeries.FirstOrDefault(s => s.Surgery == _selected);
        if (surgery == null)
            return;

        foreach (var step in surgery.Steps)
        {
            if (!_proto.TryIndex(step.Step, out var proto))
                continue;

            var button = new Button
            {
                Text = Loc.GetString(proto.Name),
                Disabled = step.Status != SurgeryStepStatus.Available,
                Modulate = step.Status switch
                {
                    SurgeryStepStatus.Completed => Color.LimeGreen,
                    SurgeryStepStatus.Locked => Color.Gray,
                    _ => Color.White,
                },
            };

            if (proto.Description is { } desc)
                button.ToolTip = Loc.GetString(desc);

            var surgeryId = surgery.Surgery;
            var stepId = step.Step;
            button.OnPressed += _ => OnStepChosen?.Invoke(surgeryId, stepId);

            StepList.AddChild(button);
        }
    }
}
