using System.Linq;
using Content.Client.Lathe.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._MalinovStation.Surgery;
using Content.Shared.Body;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._MalinovStation.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : FancyWindow
{
    [Dependency] private IEntityManager _entities = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private readonly SurgerySystem _system;

    public event Action<ProtoId<SurgeryPrototype>, ProtoId<SurgeryStepPrototype>>? OnStepChosen;

    /// <summary>Fallback names for a structural part category when the patient currently has no such
    /// part - a live part instead uses its own entity name, same as anywhere else in the game.</summary>
    private static readonly Dictionary<string, string> PartFallbackNames = new()
    {
        ["Head"] = "surgery-part-head-name",
        ["Torso"] = "surgery-part-torso-name",
        ["ArmLeft"] = "surgery-part-arm-left-name",
        ["ArmRight"] = "surgery-part-arm-right-name",
        ["LegLeft"] = "surgery-part-leg-left-name",
        ["LegRight"] = "surgery-part-leg-right-name",
    };

    private EntityUid _patient;
    private List<PartDisplay> _parts = new();
    private List<SurgeryDisplay> _surgeries = new();
    private ProtoId<OrganCategoryPrototype>? _selectedPart;
    private ProtoId<SurgeryPrototype>? _selectedSurgery;
    private ViewType _view = ViewType.Parts;

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entities.System<SurgerySystem>();

        PartsButton.OnPressed += _ => SetView(ViewType.Parts);
        SurgeriesButton.OnPressed += _ => SetView(ViewType.Surgeries);
        StepsButton.OnPressed += _ => SetView(ViewType.Steps);
    }

    public void SetPatient(EntityUid patient)
    {
        _patient = patient;
    }

    public void Populate(SurgeryBuiState state)
    {
        _parts = state.Parts;
        _surgeries = state.Surgeries;

        if (_selectedSurgery is { } sel && _surgeries.All(s => s.Surgery != sel))
            _selectedSurgery = null;

        if (_selectedPart is { } part && _parts.All(p => p.Category != part))
            _selectedPart = null;

        if (_selectedPart == null && _view != ViewType.Parts)
            _view = ViewType.Parts;
        else if (_selectedSurgery == null && _view == ViewType.Steps)
            _view = ViewType.Surgeries;

        RebuildParts();
        RebuildSurgeries();
        RebuildSteps();
        SetView(_view);
    }

    /// <summary>
    /// Re-checks whether the currently-selected step can actually be performed right now (held tools,
    /// posture) using the local player - called live as the player swaps items in/out of their hands,
    /// without waiting on a server round-trip.
    /// </summary>
    public void RefreshValidity()
    {
        RebuildSteps();
        UpdateDisabledPanel();
    }

    /// <summary>The patient's own entity name if this part is currently attached, otherwise a fallback
    /// name for the category itself.</summary>
    private string GetPartName(PartDisplay part)
    {
        if (part.Entity is { } netEntity && _entities.TryGetEntity(netEntity, out var entity))
            return _entities.GetComponent<MetaDataComponent>(entity!.Value).EntityName;

        return PartFallbackNames.TryGetValue(part.Category.Id, out var locId) ? Loc.GetString(locId) : part.Category.Id;
    }

    private void RebuildParts()
    {
        PartList.DisposeAllChildren();

        foreach (var part in _parts)
        {
            var button = new Button
            {
                Text = GetPartName(part),
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
            };

            var category = part.Category;
            button.OnPressed += _ =>
            {
                _selectedPart = category;
                _selectedSurgery = null;
                RebuildSurgeries();
                RebuildSteps();
                SetView(ViewType.Surgeries);
            };

            PartList.AddChild(button);
        }

        if (_parts.Count == 0)
        {
            PartList.AddChild(new Label
            {
                Text = Loc.GetString("surgery-window-no-surgeries"),
                HorizontalAlignment = HAlignment.Center,
                StyleClasses = { "LabelSubText" },
            });
        }
    }

    private void RebuildSurgeries()
    {
        SurgeryList.DisposeAllChildren();

        foreach (var surgery in _surgeries)
        {
            if (surgery.Part != _selectedPart || !_proto.TryIndex(surgery.Surgery, out var proto))
                continue;

            // A surgery disappears from the list entirely once its last step completes (see
            // SurgerySystem.GetSurgeriesToShow), so the only distinguishable state here is
            // "not yet started" vs "partway through" - tint the latter to make it stand out.
            var inProgress = surgery.Steps.Any(s => s.Status == SurgeryStepStatus.Completed);

            var button = new Button
            {
                Text = Loc.GetString(proto.Name),
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
            };

            if (inProgress)
                button.Modulate = Color.Orange;

            var id = surgery.Surgery;
            button.OnPressed += _ =>
            {
                _selectedSurgery = id;
                RebuildSteps();
                SetView(ViewType.Steps);
            };

            SurgeryList.AddChild(button);
        }
    }

    private void RebuildSteps()
    {
        StepList.DisposeAllChildren();

        var surgery = _surgeries.FirstOrDefault(s => s.Surgery == _selectedSurgery);
        if (surgery == null || !_proto.TryIndex(surgery.Surgery, out var surgeryProto))
            return;

        var localUser = _player.LocalEntity;

        foreach (var step in surgery.Steps)
        {
            if (!_proto.TryIndex(step.Step, out var proto))
                continue;

            var status = step.Status;
            string? tooltip = proto.Description is { } desc ? Loc.GetString(desc) : null;
            var disabled = status != SurgeryStepStatus.Available;

            // The server only knows step order (Locked/Available/Completed). For the one step that's
            // actually next, ask the shared system - using our own held items - whether it's really
            // performable right now, same logic the server itself gates the DoAfter with.
            if (status == SurgeryStepStatus.Available && localUser is { } user &&
                !_system.TryValidateStep(user, _patient, surgeryProto, proto, out _, out var reason))
            {
                disabled = true;
                if (reason != null)
                    tooltip = Loc.GetString(reason);
            }

            var button = new Button
            {
                Text = Loc.GetString(proto.Name),
                HorizontalExpand = true,
                Disabled = disabled,
                Margin = new Thickness(0, 0, 0, 2),
            };

            button.Modulate = status switch
            {
                SurgeryStepStatus.Completed => Color.LimeGreen,
                SurgeryStepStatus.Locked => Color.Gray,
                _ when disabled => Color.IndianRed,
                _ => Color.White,
            };

            if (tooltip != null)
            {
                var tooltipText = tooltip;
                button.TooltipSupplier = _ => new RecipeTooltip(tooltipText);
            }

            var surgeryId = surgery.Surgery;
            var stepId = step.Step;
            button.OnPressed += _ => OnStepChosen?.Invoke(surgeryId, stepId);

            StepList.AddChild(button);
        }
    }

    private void UpdateDisabledPanel()
    {
        if (_patient == default || !_entities.EntityExists(_patient) || _system.IsLyingDown(_patient))
        {
            DisabledPanel.Visible = false;
            DisabledPanel.MouseFilter = MouseFilterMode.Ignore;
            return;
        }

        DisabledPanel.Visible = true;
        DisabledPanel.MouseFilter = MouseFilterMode.Stop;

        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("surgery-window-needs-lying-down"));
        DisabledLabel.SetMessage(msg);
    }

    private void SetView(ViewType view)
    {
        _view = view;

        PartList.Visible = view == ViewType.Parts;
        PartsButton.Disabled = view == ViewType.Parts;

        SurgeryList.Visible = view == ViewType.Surgeries;
        SurgeriesButton.Disabled = view == ViewType.Surgeries || _selectedPart == null;

        StepList.Visible = view == ViewType.Steps;
        StepsButton.Disabled = view == ViewType.Steps || _selectedSurgery == null;

        Title = BuildTitle();
        UpdateDisabledPanel();
    }

    private string BuildTitle()
    {
        if (_selectedSurgery is { } surgeryId && _proto.TryIndex(surgeryId, out var surgeryProto))
            return Loc.GetString("surgery-window-title-with-surgery", ("surgery", Loc.GetString(surgeryProto.Name)));

        if (_selectedPart is { } partCategory)
        {
            var part = _parts.FirstOrDefault(p => p.Category == partCategory);
            if (part != null)
                return Loc.GetString("surgery-window-title-with-part", ("part", GetPartName(part)));
        }

        return Loc.GetString("surgery-window-title");
    }

    private enum ViewType
    {
        Parts,
        Surgeries,
        Steps,
    }
}
