using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MalinovStation.Lobby.Tiles;

/// <summary>
/// Players tile: how many players are online and, before the round, how many are ready;
/// during the round, how many are in it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MalinovPlayersTileWidget : BoxContainer, IMalinovLobbyTileWidget
{
    [Dependency] private ILocalizationManager _loc = default!;

    public MalinovPlayersTileWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Refresh(in MalinovLobbyTileContext context)
    {
        var info = context.LobbyInfo;
        var unknown = _loc.GetString("malinov-lobby-tile-value-unknown");

        OnlineValue.Text = info?.PlayerCount.ToString() ?? unknown;

        if (context.IsGameStarted)
        {
            CountValue.Text = info?.InGameCount.ToString() ?? unknown;
            CountCaption.Text = _loc.GetString("malinov-lobby-tile-players-in-game");
            return;
        }

        CountValue.Text = info?.ReadyCount.ToString() ?? unknown;
        CountCaption.Text = _loc.GetString("malinov-lobby-tile-players-ready");
    }
}
