using Content.Client.Changelog;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._MalinovStation.Lobby.Tiles;

/// <summary>
/// One line of a changelog entry: what kind of change it is and what changed.
/// </summary>
public sealed record MalinovChangelogLine(ChangelogManager.ChangelogLineType Type, string Message, bool Experimental);

/// <summary>
/// A changelog entry as the what's new tile shows it.
/// </summary>
public sealed record MalinovChangelogItem(int Id, string Author, DateTime Time, IReadOnlyList<MalinovChangelogLine> Lines);

/// <summary>
/// Lobby tile with the newest entries of the main changelog. Entries the player has not read yet are marked,
/// and a button opens the whole changelog, which counts as reading it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MalinovChangelogTileWidget : BoxContainer
{
    [Dependency] private ChangelogManager _changelog = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private ILogManager _log = default!;
    [Dependency] private IUserInterfaceManager _ui = default!;

    /// <summary>
    /// Entries shown at most.
    /// </summary>
    public const int MaxEntries = 5;

    // Label the changelog parser puts on changes from pull requests marked experimental.
    private const string ExperimentalLabel = "Intent: Experimental";

    private readonly List<MalinovChangelogItem> _latest = new();
    private bool _loadStarted;
    private bool _loaded;

    /// <summary>
    /// Entries the tile shows, newest first.
    /// </summary>
    public IReadOnlyList<MalinovChangelogItem> Latest => _latest;

    public MalinovChangelogTileWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        OpenButton.OnPressed += OnOpenPressed;
    }

    /// <summary>
    /// Fills <paramref name="latest"/> with the newest <paramref name="count"/> of <paramref name="entries"/>, newest first.
    /// </summary>
    public static void SelectLatest(IEnumerable<MalinovChangelogItem> entries, int count, List<MalinovChangelogItem> latest)
    {
        latest.Clear();
        latest.AddRange(entries);
        latest.Sort((a, b) => b.Id.CompareTo(a.Id));
        if (latest.Count > count)
            latest.RemoveRange(count, latest.Count - count);
    }

    /// <summary>
    /// Whether <paramref name="entry"/> came after the changelog was last read, while the player has not read it since.
    /// </summary>
    public static bool IsNew(MalinovChangelogItem entry, int lastReadId, bool hasNewEntries)
    {
        return hasNewEntries && entry.Id > lastReadId;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _changelog.NewChangelogEntriesChanged += OnNewEntriesChanged;
        if (!_loadStarted)
            LoadEntries();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _changelog.NewChangelogEntriesChanged -= OnNewEntriesChanged;
    }

    private void OnNewEntriesChanged()
    {
        // Until the entries are read there is nothing to mark.
        if (_loaded)
            ShowEntries();
    }

    private void OnOpenPressed(BaseButton.ButtonEventArgs args)
    {
        _ui.GetUIController<ChangelogUIController>().OpenWindow();
    }

    /// <summary>
    /// Reads the changelog files in the background, as the changelog window does, and shows the main changelog.
    /// </summary>
    private async void LoadEntries()
    {
        _loadStarted = true;
        try
        {
            var changelogs = await _changelog.LoadChangelog();
            foreach (var changelog in changelogs)
            {
                if (changelog.Name != ChangelogManager.MainChangelogName)
                    continue;

                SetEntries(ToItems(changelog));
                return;
            }

            SetEntries(Array.Empty<MalinovChangelogItem>());
        }
        catch (Exception e)
        {
            _log.GetSawmill("lobby").Error($"Failed to read the changelog for the lobby: {e}");
        }
    }

    private void SetEntries(IEnumerable<MalinovChangelogItem> entries)
    {
        SelectLatest(entries, MaxEntries, _latest);
        _loaded = true;
        ShowEntries();
    }

    private void ShowEntries()
    {
        Entries.RemoveAllChildren();
        EmptyLabel.Visible = _latest.Count == 0;

        foreach (var entry in _latest)
        {
            var header = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 6,
                Margin = new Thickness(4, 4, 4, 0),
            };
            header.AddChild(new Label
            {
                Text = _loc.GetString("malinov-lobby-changelog-entry", ("author", entry.Author), ("day", GetDayText(entry.Time))),
                StyleClasses = { StyleClass.LabelSubHeading },
            });

            if (IsNew(entry, _changelog.LastReadId, _changelog.NewChangelogEntries))
            {
                header.AddChild(new Label
                {
                    Text = _loc.GetString("malinov-lobby-changelog-new"),
                    StyleClasses = { StyleClass.Highlight },
                });
            }

            Entries.AddChild(header);

            foreach (var line in entry.Lines)
            {
                var lineControl = new ChangelogEntry();
                lineControl.SetText(FormattedMessage.FromUnformatted(line.Message));
                lineControl.SetIcons(line.Type, line.Experimental);
                Entries.AddChild(lineControl);
            }
        }
    }

    /// <summary>
    /// Today, yesterday or the date, the way the changelog window names days.
    /// </summary>
    private string GetDayText(DateTime time)
    {
        var day = time.ToLocalTime().Date;
        var today = DateTime.Today;
        if (day == today)
            return _loc.GetString("changelog-today");

        return day == today.AddDays(-1) ? _loc.GetString("changelog-yesterday") : day.ToShortDateString();
    }

    private static List<MalinovChangelogItem> ToItems(ChangelogManager.Changelog changelog)
    {
        var items = new List<MalinovChangelogItem>(changelog.Entries.Count);
        foreach (var entry in changelog.Entries)
        {
            var experimental = entry.Labels.Contains(ExperimentalLabel);
            var lines = new List<MalinovChangelogLine>(entry.Changes.Count);
            foreach (var change in entry.Changes)
            {
                lines.Add(new MalinovChangelogLine(change.Type, change.Message, experimental));
            }

            items.Add(new MalinovChangelogItem(entry.Id, entry.Author, entry.Time, lines));
        }

        return items;
    }
}
