using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MalinovStation.Lobby.Tiles;

/// <summary>
/// Server tile: the lobby title and the server links. Round details live in the round and players tiles.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MalinovServerTileWidget : BoxContainer, IMalinovLobbyTileWidget
{
    public MalinovServerTileWidget()
    {
        RobustXamlLoader.Load(this);
    }

    public void Refresh(in MalinovLobbyTileContext context)
    {
        ServerName.Text = context.ServerTitle;
    }
}
