using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MalinovStation.Lobby.Tiles;

/// <summary>
/// Round start tile: the countdown, the observe button and the ready button,
/// which turns into the late join button once the round runs.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MalinovReadyTileWidget : BoxContainer, IMalinovLobbyTileWidget
{
    [Dependency] private ILocalizationManager _loc = default!;

    // What the ready button shows now. Per-second refreshes leave it alone until this changes,
    // so a click that waits for the server is not reverted in the meantime.
    private (bool Started, bool Ready, bool LateJoinDisallowed)? _shownReadyState;
    private LocId? _shownPlaytimeComment;
    private float _shownPlaytimeHours;

    /// <summary>
    /// Where the buttons send their requests; without it the buttons do nothing.
    /// </summary>
    public IMalinovLobbyActions? Actions { get; set; }

    /// <summary>
    /// The round is about to start and the player is not ready yet.
    /// </summary>
    public bool Accented { get; private set; }

    // The XAML loader needs a parameterless constructor.
    public MalinovReadyTileWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ReadyButton.OnToggled += OnReadyToggled;
        ReadyButton.OnPressed += OnReadyPressed;
    }

    public MalinovReadyTileWidget(IMalinovLobbyActions actions) : this()
    {
        Actions = actions;
    }

    public void Refresh(in MalinovLobbyTileContext context)
    {
        RefreshReadyButton(context);
        RefreshCountdown(context);
        RefreshPlaytimeComment(context.PlaytimeMinutesToday);
    }

    private void OnReadyToggled(BaseButton.ButtonToggledEventArgs args)
    {
        Actions?.TrySetReady(args.Pressed);
    }

    private void OnReadyPressed(BaseButton.ButtonEventArgs args)
    {
        // A toggle press changes readiness and is handled by OnReadyToggled; a plain press means join.
        if (ReadyButton.ToggleMode)
            return;

        Actions?.TryJoinGame();
    }

    private void RefreshReadyButton(in MalinovLobbyTileContext context)
    {
        var state = (context.IsGameStarted, context.AreWeReady, context.DisallowedLateJoin);
        if (_shownReadyState == state)
            return;

        _shownReadyState = state;

        if (context.IsGameStarted)
        {
            ReadyButton.ToggleMode = false;
            ReadyButton.Pressed = false;
            ReadyButton.Disabled = context.DisallowedLateJoin;
            ReadyButton.Text = _loc.GetString("lobby-state-ready-button-join-state");
            ObserveButton.Disabled = false;
            return;
        }

        ReadyButton.ToggleMode = true;
        ReadyButton.Pressed = context.AreWeReady;
        ReadyButton.Disabled = false;
        ReadyButton.Text = _loc.GetString(context.AreWeReady
            ? "lobby-state-player-status-ready"
            : "lobby-state-player-status-not-ready");
        ObserveButton.Disabled = true;
    }

    private void RefreshCountdown(in MalinovLobbyTileContext context)
    {
        var countdown = MalinovLobbyStatusText.GetCountdown(
            context.IsGameStarted,
            context.Paused,
            context.StartTime,
            context.CurTime);

        Accented = MalinovLobbyStatusText.NeedsReadyAccent(countdown, context.AreWeReady);
        CountdownLabel.Visible = countdown.Kind != MalinovLobbyCountdownKind.Hidden;
        CountdownLabel.Text = countdown.Kind switch
        {
            MalinovLobbyCountdownKind.Hidden => string.Empty,
            MalinovLobbyCountdownKind.Soon => _loc.GetString("lobby-state-soon"),
            MalinovLobbyCountdownKind.Paused => _loc.GetString("lobby-state-round-start-countdown-text",
                ("timeLeft", _loc.GetString("lobby-state-paused"))),
            _ => _loc.GetString("lobby-state-round-start-countdown-text",
                ("timeLeft", MalinovLobbyStatusText.FormatTimeLeft(countdown.Left))),
        };
    }

    private void RefreshPlaytimeComment(float minutesToday)
    {
        var comment = MalinovLobbyStatusText.GetPlaytimeComment(minutesToday);
        PlaytimeComment.Visible = comment != null;
        if (comment is not { } key)
            return;

        var hours = MathF.Round(minutesToday / 60f, 1);
        if (key == _shownPlaytimeComment && hours.Equals(_shownPlaytimeHours))
            return;

        _shownPlaytimeComment = key;
        _shownPlaytimeHours = hours;
        PlaytimeComment.SetMarkup(_loc.GetString(key, ("hours", hours)));
    }
}
