using Content.Client.Message;
using Content.Shared._MalinovStation.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MalinovStation.Lobby.Tiles;

/// <summary>
/// Round tile: round number, map, game mode with its description and how long the round has run.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MalinovRoundTileWidget : BoxContainer, IMalinovLobbyTileWidget
{
    [Dependency] private ILocalizationManager _loc = default!;

    // Round information changes rarely; its markup is rebuilt only when the server sends a new one.
    private MalinovLobbyInfoEvent? _shownInfo;

    public MalinovRoundTileWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Refresh(in MalinovLobbyTileContext context)
    {
        if (!ReferenceEquals(context.LobbyInfo, _shownInfo))
            ShowInfo(context.LobbyInfo);

        if (!context.IsGameStarted)
        {
            RoundTimeLabel.Text = _loc.GetString("lobby-state-player-status-round-not-started");
            return;
        }

        var roundTime = context.CurTime - context.RoundStartTime;
        RoundTimeLabel.Text = _loc.GetString("lobby-state-player-status-round-time",
            ("hours", roundTime.Hours),
            ("minutes", roundTime.Minutes));
    }

    private void ShowInfo(MalinovLobbyInfoEvent? info)
    {
        _shownInfo = info;

        NumberLabel.Visible = info != null;
        MapLabel.Visible = info != null;
        ModeLabel.Visible = !string.IsNullOrEmpty(info?.ModeTitle);
        ModeDescriptionLabel.Visible = ModeLabel.Visible && !string.IsNullOrEmpty(info?.ModeDescription);

        if (info == null)
            return;

        NumberLabel.SetMarkup(_loc.GetString("malinov-lobby-tile-round-number", ("roundId", info.RoundId)));

        var map = MalinovLobbyStatusText.JoinMapNames(info.MapNames);
        MapLabel.SetMarkup(map == null
            ? _loc.GetString("malinov-lobby-tile-round-no-map")
            : _loc.GetString("malinov-lobby-tile-round-map", ("map", map)));

        if (ModeLabel.Visible)
            ModeLabel.SetMarkup(_loc.GetString("malinov-lobby-tile-round-mode", ("mode", _loc.GetString(info.ModeTitle!))));

        if (ModeDescriptionLabel.Visible)
        {
            ModeDescriptionLabel.SetMarkup(_loc.GetString("malinov-lobby-tile-round-mode-description",
                ("description", _loc.GetString(info.ModeDescription!))));
        }
    }
}
