using Content.Client.Message;
using Content.Shared.GameTicking.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._MalinovStation.Lobby.Tiles;

/// <summary>
/// Credits tile: the game credits button and who made the lobby music and background shown now.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MalinovCreditsTileWidget : BoxContainer, IMalinovLobbyTileWidget
{
    [Dependency] private ILocalizationManager _loc = default!;

    // Markup is rebuilt only when the song or the background changes, not on every refresh.
    private MalinovLobbySong? _shownSong;
    private LobbyBackgroundPrototype? _shownBackground;

    public MalinovCreditsTileWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ShowSong(null);
        ShowBackground(null);
    }

    public void Refresh(in MalinovLobbyTileContext context)
    {
        if (context.Song != _shownSong)
            ShowSong(context.Song);

        if (context.Background != _shownBackground)
            ShowBackground(context.Background);
    }

    private void ShowSong(MalinovLobbySong? song)
    {
        _shownSong = song;

        if (song is not { } playing)
        {
            SongLabel.SetMarkup(_loc.GetString("lobby-state-song-no-song-text"));
            return;
        }

        // Title and artist come from the audio file, so they are escaped before going into markup.
        var title = string.IsNullOrEmpty(playing.Title)
            ? _loc.GetString("lobby-state-song-unknown-title")
            : FormattedMessage.EscapeText(playing.Title);
        var artist = string.IsNullOrEmpty(playing.Artist)
            ? _loc.GetString("lobby-state-song-unknown-artist")
            : FormattedMessage.EscapeText(playing.Artist);

        SongLabel.SetMarkup(_loc.GetString("lobby-state-song-text", ("songTitle", title), ("songArtist", artist)));
    }

    private void ShowBackground(LobbyBackgroundPrototype? background)
    {
        _shownBackground = background;

        if (background == null)
        {
            BackgroundLabel.SetMarkup(_loc.GetString("lobby-state-background-no-background-text"));
            return;
        }

        BackgroundLabel.SetMarkup(_loc.GetString("lobby-state-background-text",
            ("backgroundTitle", _loc.GetString(background.Title)),
            ("backgroundArtist", _loc.GetString(background.Artist))));
    }
}
