using System.Linq;
using Content.Client.Audio.Midi;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;

namespace Content.Client.Instruments.UI;

[GenerateTypedNameReferences]
public sealed partial class MidiCollectionUtilsControl : Control
{
    [Dependency] private MidiFileCollectionManager _midiCollection = default!;
    [Dependency] private IResourceManager _resourceManager = default!;

    public MidiCollectionUtilsControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Malinov edit - library subscriptions follow this control's tree lifetime.

        DeleteAllButton.StyleClasses.Add(StyleClass.Negative);

        OpenDirectoryButton.OnPressed += OnOpenDirectoryButtonPressed;
        ReloadCollectionButton.OnPressed += OnReloadCollectionButtonPressed;
        DeleteAllButton.OnPressed += OnDeleteAllButtonPressed;

        UpdateCount();
    }

    private void OnOpenDirectoryButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        _resourceManager.UserData.OpenOsWindow(MidiFileCollectionManager.UserMidiDirectory);
    }

    private void OnReloadCollectionButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        _midiCollection.ReloadLibrary();
    }

    private void OnDeleteAllButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        _midiCollection.RemoveAllMidiFiles();
    }

    private void UpdateCount()
    {
        MidiCountLabel.Text = Loc.GetString(
            "instruments-component-midi-file-collection-size-label",
            ("count", _midiCollection.GetMidiFiles().Count()));
    }
}
