using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map.Components;

namespace Content.Client.Administration.UI.Tabs.AtmosTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class AddAtmosWindow : DefaultWindow
    {
        [Dependency] private IPlayerManager _players = default!;
        [Dependency] private IEntityManager _entities = default!;

        private readonly List<Entity<MapGridComponent>> _data = new();

        public AddAtmosWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            // Malinov added start - subscribe once for the lifetime of the window.
            GridOptions.OnItemSelected += eventArgs => GridOptions.SelectId(eventArgs.Id);
            SubmitButton.OnPressed += SubmitButtonOnOnPressed;
            // Malinov added end
        }

        protected override void EnteredTree()
        {
            _data.Clear();
            GridOptions.Clear(); // Malinov added - rebuild options alongside their backing data.

            var player = _players.LocalEntity;
            var playerGrid = _entities.GetComponentOrNull<TransformComponent>(player)?.GridUid;
            var query = IoCManager.Resolve<IEntityManager>().AllEntityQueryEnumerator<MapGridComponent>();

            while (query.MoveNext(out var uid, out var grid))
            {
                _data.Add((uid, grid));
                GridOptions.AddItem($"{uid} {(playerGrid == uid ? Loc.GetString($"admin-ui-atmos-grid-current") : "")}");
            }

            SubmitButton.Disabled = _data.Count == 0; // Malinov edit - an empty grid list cannot be submitted.
        }

        private void SubmitButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
        {
            // Malinov added start - the grid list may be empty or its selected grid may have been deleted.
            if ((uint) GridOptions.SelectedId >= (uint) _data.Count ||
                !_entities.HasComponent<MapGridComponent>(_data[GridOptions.SelectedId].Owner))
                return;
            // Malinov added end

            var selectedGrid = _data[GridOptions.SelectedId].Owner;
            IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand($"addatmos {_entities.GetNetEntity(selectedGrid)}");
        }
    }
}
