using Content.Shared._MalinovStation.Messenger;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using System.Numerics;

namespace Content.Client._MalinovStation.Messenger;

[GenerateTypedNameReferences]
public sealed partial class MalinovMessengerUiFragment : BoxContainer
{
    public event Action<string?>? OnContactSelected;
    public event Action<string, string>? OnSendMessage;
    public event Action? OnCloseChat;

    private List<MalinovMessengerContact> _contacts = new();
    private string? _selectedContact;
    private bool _updating;
    private bool _pendingScrollToBottom;
    private bool _justSent;
    private bool _prevHadMessages;
    private string? _prevSelectedContact;
    private long _lastOutgoingId;

    private const float AtBottomThreshold = 32f;

    private static readonly Color IncomingBubbleColor = Color.FromHex("#2b3a42");
    private static readonly Color OutgoingBubbleColor = Color.FromHex("#2b422b");

    private static readonly Color MutedOverlayColor = new(0.52f, 0.04f, 0.04f, 0.96f);

    private const float MessageMaxWidth = 400f;

    [Dependency] private IConfigurationManager _cfg = default!;

    public MalinovMessengerUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        ContactsList.OnItemSelected += OnItemSelected;
        SendButton.OnPressed += _ => TrySend();
        Input.OnTextEntered += _ => TrySend();
        Input.IsValid = s => s.Length <= _cfg.GetCVar(CCVars.MalinovMessengerMaxMessageLength);
        CloseChatButton.OnPressed += _ =>
        {
            if (_selectedContact == null)
                return;

            Input.Clear();
            OnCloseChat?.Invoke();
        };
        ChatScrollContainer.OnScrolled += OnChatScrolled;
        MutedOverlay.ModulateSelfOverride = MutedOverlayColor;

        UpdateState(new MalinovMessengerUiState());
    }

    public void UpdateState(MalinovMessengerUiState state)
    {
        _updating = true;
        _contacts = state.Contacts;
        _selectedContact = state.SelectedContact;
        CloseChatButton.Visible = _selectedContact != null;

        if (!string.IsNullOrEmpty(state.Status) && state.Contacts.Count == 0)
        {
            StatusLabel.Text = Loc.GetString(state.Status);
            StatusLabel.Visible = true;
            MainContainer.Visible = false;
            _updating = false;
            return;
        }

        StatusLabel.Visible = false;
        MainContainer.Visible = true;

        MutedOverlay.Visible = state.IsMuted;
        Input.Editable = !state.IsMuted;
        SendButton.Disabled = state.IsMuted;

        if (!string.IsNullOrEmpty(state.Status) && !state.IsMuted)
        {
            ErrorLabel.Text = Loc.GetString(state.Status);
            ErrorLabel.Visible = true;
        }
        else
        {
            ErrorLabel.Visible = false;
        }

        ContactsList.Clear();

        if (state.Contacts.Count == 0)
        {
            ChatHeaderLabel.Text = Loc.GetString("malinov-messenger-chat-header-empty");
            ChatContainer.RemoveAllChildren();
            ChatContainer.AddChild(new Label { Text = Loc.GetString("malinov-messenger-session-empty") });
            _updating = false;
            return;
        }

        for (var i = 0; i < state.Contacts.Count; i++)
        {
            var contact = state.Contacts[i];

            ContactsList.AddItem(Loc.GetString(contact.HasUnread
                ? "malinov-messenger-contact-format-unread"
                : "malinov-messenger-contact-format",
                ("name", contact.Name)));

            if (contact.Name == _selectedContact)
                ContactsList[i].Selected = true;
        }

        ChatHeaderLabel.Text = _selectedContact != null
            ? Loc.GetString("malinov-messenger-chat-header", ("name", _selectedContact))
            : Loc.GetString("malinov-messenger-chat-header-empty");

        ChatContainer.RemoveAllChildren();

        if (state.Messages.Count == 0)
        {
            ChatContainer.AddChild(new Label { Text = Loc.GetString("malinov-messenger-session-empty") });
            _pendingScrollToBottom = false;
            _justSent = false;
            _prevHadMessages = false;
            _lastOutgoingId = 0;
        }
        else
        {
            foreach (var message in state.Messages)
            {
                ChatContainer.AddChild(BuildMessageRow(message));
            }

            var conversationChanged = _prevSelectedContact != state.SelectedContact;
            if (conversationChanged)
                _lastOutgoingId = 0;

            // A new outgoing message always scrolls the chat to it. Tracked by id so the
            // scroll survives the full ChatContainer rebuild regardless of when _justSent
            // gets cleared by intermediate state updates.
            var last = state.Messages[^1];
            var newOutgoing = last.Outgoing && last.Id != _lastOutgoingId;
            if (newOutgoing)
                _lastOutgoingId = last.Id;

            var stickToBottom = newOutgoing || _justSent || conversationChanged || !_prevHadMessages || WasAtBottom();
            _justSent = false;
            _prevHadMessages = true;
            _prevSelectedContact = state.SelectedContact;

            if (stickToBottom)
            {
                _pendingScrollToBottom = true;
                ChatScrollContainer.SetScrollValue(new Vector2(0, float.MaxValue));
            }
        }

        _updating = false;
    }

    private static Control BuildMessageRow(MalinovMessengerMessage message)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var bubble = new PanelContainer
        {
            StyleClasses = { "BackgroundPanel" },
            ModulateSelfOverride = message.Outgoing ? OutgoingBubbleColor : IncomingBubbleColor,
            Margin = new Thickness(2, 2, 2, 2),
        };

        var content = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
        };

        var senderLabel = new Label
        {
            Text = message.SenderName,
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Left,
        };

        var textLabel = new RichTextLabel
        {
            MaxWidth = MessageMaxWidth,
        };
        textLabel.SetMessage(message.Text);

        var time = message.Timestamp.ToString(@"hh\:mm");
        var timeLabel = new Label
        {
            Text = Loc.GetString("malinov-messenger-message-time-format", ("time", time)),
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Right,
        };

        content.AddChild(senderLabel);
        content.AddChild(textLabel);
        content.AddChild(timeLabel);
        bubble.AddChild(content);

        var spacer = new Control { HorizontalExpand = true };

        if (message.Outgoing)
        {
            row.AddChild(spacer);
            row.AddChild(bubble);
        }
        else
        {
            row.AddChild(bubble);
            row.AddChild(spacer);
        }

        return row;
    }

    private void OnItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_updating)
            return;

        if (args.ItemIndex < 0 || args.ItemIndex >= _contacts.Count)
            return;

        _selectedContact = _contacts[args.ItemIndex].Name;
        OnContactSelected?.Invoke(_selectedContact);
    }

    private void TrySend()
    {
        if (MutedOverlay.Visible)
            return;

        var text = Input.Text.Trim();

        if (string.IsNullOrWhiteSpace(text) || _selectedContact == null)
            return;

        _justSent = true;
        OnSendMessage?.Invoke(_selectedContact, text);
        Input.Clear();
    }

    private bool TryGetScrollBottom(out float bottom)
    {
        bottom = Math.Max(0f, ChatContainer.PixelHeight - ChatScrollContainer.PixelHeight);
        if (bottom <= 0f)
        {
            _pendingScrollToBottom = false;
            return false;
        }

        return true;
    }

    private bool WasAtBottom()
    {
        return TryGetScrollBottom(out var bottom)
               && MathHelper.CloseTo(ChatScrollContainer.GetScrollValue().Y, bottom, AtBottomThreshold);
    }

    private void OnChatScrolled()
    {
        if (!_pendingScrollToBottom)
            return;

        if (!TryGetScrollBottom(out var bottom))
            return;

        var current = ChatScrollContainer.GetScrollValue().Y;
        if (MathHelper.CloseTo(current, bottom, AtBottomThreshold))
        {
            // Bottom reached; stop re-asserting to avoid an endless layout loop.
            _pendingScrollToBottom = false;
            return;
        }

        // Late layout pass means MaxValue is now fresh, so land exactly at the bottom.
        ChatScrollContainer.SetScrollValue(new Vector2(0, float.MaxValue));
    }
}
