using Content.Shared._MalinovStation.Messenger;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client._MalinovStation.Messenger;

[GenerateTypedNameReferences]
public sealed partial class MalinovMessengerUiFragment : BoxContainer
{
    public event Action<string?>? OnContactSelected;
    public event Action<string, string>? OnSendMessage;

    private List<MalinovMessengerContact> _contacts = new();
    private HashSet<string> _onlineNames = new();
    private string? _selectedContact;
    private bool _updating;

    private static readonly Color IncomingBubbleColor = Color.FromHex("#2b3a42");
    private static readonly Color OutgoingBubbleColor = Color.FromHex("#2b422b");

    private const float MessageMaxWidth = 256f;

    [Dependency] private IConfigurationManager _cfg = default!;

    public MalinovMessengerUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        HeaderLabel.Text = Loc.GetString("malinov-messenger-contacts-header");

        ContactsList.OnItemSelected += OnItemSelected;
        SendButton.OnPressed += _ => TrySend();
        Input.OnTextEntered += _ => TrySend();
        Input.IsValid = s => s.Length <= _cfg.GetCVar(CCVars.MalinovMessengerMaxMessageLength);

        UpdateState(new MalinovMessengerUiState());
    }

    public void UpdateState(MalinovMessengerUiState state)
    {
        _updating = true;
        _contacts = state.Contacts;
        _onlineNames = state.OnlineNames;
        _selectedContact = state.SelectedContact;

        if (!string.IsNullOrEmpty(state.ServerStatus))
        {
            ServerStatusLabel.Text = Loc.GetString(state.ServerStatus);
            ServerStatusLabel.Visible = true;
        }
        else
        {
            ServerStatusLabel.Visible = false;
        }

        if (!string.IsNullOrEmpty(state.Status) && state.Contacts.Count == 0)
        {
            StatusLabel.Text = Loc.GetString(state.Status);
            StatusLabel.Visible = true;
            MainContainer.Visible = false;
            _updating = false;
            return;
        }

        StatusLabel.Visible = false;
        MainContainer.Visible = true;

        if (!string.IsNullOrEmpty(state.Status))
        {
            ErrorLabel.Text = Loc.GetString(state.Status);
            ErrorLabel.Visible = true;
        }
        else
        {
            ErrorLabel.Visible = false;
        }

        ContactsList.Clear();

        if (state.Contacts.Count == 0)
        {
            ChatHeaderLabel.Text = Loc.GetString("malinov-messenger-chat-header-empty");
            ChatContainer.RemoveAllChildren();
            ChatContainer.AddChild(new Label { Text = Loc.GetString("malinov-messenger-session-empty") });
            _updating = false;
            return;
        }

        for (var i = 0; i < state.Contacts.Count; i++)
        {
            var contact = state.Contacts[i];
            var isOnline = state.OnlineNames.Contains(contact.Name);
            var statusKey = isOnline
                ? "malinov-messenger-status-online"
                : "malinov-messenger-status-offline";
            var statusText = Loc.GetString(statusKey);

            ContactsList.AddItem(Loc.GetString("malinov-messenger-contact-format-status",
                ("name", contact.Name),
                ("job", contact.JobTitle),
                ("status", statusText)));

            if (contact.Name == _selectedContact)
                ContactsList[i].Selected = true;
        }

        ChatHeaderLabel.Text = _selectedContact != null
            ? Loc.GetString("malinov-messenger-chat-header", ("name", _selectedContact))
            : Loc.GetString("malinov-messenger-chat-header-empty");

        ChatContainer.RemoveAllChildren();

        if (state.Messages.Count == 0)
        {
            ChatContainer.AddChild(new Label { Text = Loc.GetString("malinov-messenger-session-empty") });
        }
        else
        {
            foreach (var message in state.Messages)
            {
                ChatContainer.AddChild(BuildMessageRow(message));
            }
        }

        _updating = false;
    }

    private static Control BuildMessageRow(MalinovMessengerMessage message)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var bubble = new PanelContainer
        {
            StyleClasses = { "BackgroundPanel" },
            ModulateSelfOverride = message.Outgoing ? OutgoingBubbleColor : IncomingBubbleColor,
            Margin = new Thickness(2, 2, 2, 2),
        };

        var content = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
        };

        var senderLabel = new Label
        {
            Text = message.SenderName,
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Left,
        };

        var textLabel = new RichTextLabel
        {
            MaxWidth = MessageMaxWidth,
        };
        textLabel.SetMessage(message.Text);

        var time = message.Timestamp.ToString(@"hh\:mm");
        var timeLabel = new Label
        {
            Text = Loc.GetString("malinov-messenger-message-time-format", ("time", time)),
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Right,
        };

        content.AddChild(senderLabel);
        content.AddChild(textLabel);
        content.AddChild(timeLabel);
        bubble.AddChild(content);

        var spacer = new Control { HorizontalExpand = true };

        if (message.Outgoing)
        {
            row.AddChild(spacer);
            row.AddChild(bubble);
        }
        else
        {
            row.AddChild(bubble);
            row.AddChild(spacer);
        }

        return row;
    }

    private void OnItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_updating)
            return;

        if (args.ItemIndex < 0 || args.ItemIndex >= _contacts.Count)
            return;

        _selectedContact = _contacts[args.ItemIndex].Name;
        OnContactSelected?.Invoke(_selectedContact);
    }

    private void TrySend()
    {
        var text = Input.Text.Trim();

        if (string.IsNullOrWhiteSpace(text) || _selectedContact == null)
            return;

        OnSendMessage?.Invoke(_selectedContact, text);
        Input.Clear();
    }
}
