using Content.Shared._MalinovStation.Messenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MalinovStation.Messenger;

[GenerateTypedNameReferences]
public sealed partial class MalinovMessengerUiFragment : BoxContainer
{
    public MalinovMessengerUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        HeaderLabel.Text = Loc.GetString("malinov-messenger-contacts-header");
        UpdateState(new MalinovMessengerUiState());
    }

    public void UpdateState(MalinovMessengerUiState state)
    {
        if (!string.IsNullOrEmpty(state.Status))
        {
            StatusLabel.Text = Loc.GetString(state.Status);
            StatusLabel.Visible = true;
            ContactsList.Visible = false;
            PlaceholderLabel.Visible = false;
            return;
        }

        StatusLabel.Visible = false;

        if (state.Contacts.Count == 0)
        {
            ContactsList.Visible = false;
            PlaceholderLabel.Text = Loc.GetString("malinov-messenger-no-contacts");
            PlaceholderLabel.Visible = true;
            return;
        }

        PlaceholderLabel.Visible = false;
        ContactsList.Clear();

        foreach (var contact in state.Contacts)
        {
            ContactsList.AddItem(Loc.GetString("malinov-messenger-contact-format",
                ("name", contact.Name),
                ("job", contact.JobTitle)));
        }

        ContactsList.Visible = true;
    }
}
